version: "{build}"

environment:
  matrix:
    - nodejs_version: 7
    - nodejs_version: 6
    - nodejs_version: 4

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - set PATH=%APPDATA%\npm;%PATH%
  # tools versions
  - node --version
  - npm --version
  # install modules
  - npm install

test_script:
  - npm run ready

build: off
